# BOW 직접구현

In [3]:
docs=['오늘 동물원에서 코끼리 원숭이를 보고 꼬끼리 원숭이에게 사과를 줬어',
     '오늘 동물원에서 원숭이에게 사과를 줬어']

In [4]:
# 띄어쓰기로 토큰화 하기 
doc_ls=[]
for doc in docs:
    doc_ls.append(doc.split(' '))
    
from collections import defaultdict # 빈 딕셔너리를 만들어주고 
word2id = defaultdict(lambda: len(word2id))

# 토큰들을 딕셔너리에 넣어줌 
for doc in doc_ls:
    for token in doc:
        word2id[token]
word2id

defaultdict(<function __main__.<lambda>>,
            {'꼬끼리': 5,
             '동물원에서': 1,
             '보고': 4,
             '사과를': 7,
             '오늘': 0,
             '원숭이를': 3,
             '원숭이에게': 6,
             '줬어': 8,
             '코끼리': 2})

In [8]:
import numpy as np
BoW_ls =[]
for i, doc in enumerate(doc_ls):
    bow = np.zeros(len(word2id),dtype =int)
    print(bow)
    for token in doc:
        bow[word2id[token]] +=1
    BoW_ls.append(bow.tolist())
    
#1차원 배열
BoW_ls
# bow 도 먼저 0으로 세팅먼저 해주기 
#for token in doc는 딕셔너리에 해당하는 

[0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0]


[[1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 0, 0, 0, 0, 1, 1, 1]]

In [12]:
# Bow_ls 값들 나온거 가지고 뭐가 어떤 인덱스인지 모르니까 
#시각화를 해봤다
# word2_id 는 딕셔너리니까  key랑 value 로 되어 있자나
# sorted_vocab해서 하나씪 뽑아서 보자 
from IPython.core import display as ICD
import pandas as pd
sorted_vocab = sorted((value, key) for key, value in word2id.items())

print('sorted_vocab', sorted_vocab)

sorted_vocab [(0, '오늘'), (1, '동물원에서'), (2, '코끼리'), (3, '원숭이를'), (4, '보고'), (5, '꼬끼리'), (6, '원숭이에게'), (7, '사과를'), (8, '줬어')]


In [6]:
# 시각화로많이 보여줬는데, 실제로는 단어가너무 많아서 시각화 ㄴ ㅗ우..

In [13]:
vocab = []
for v in sorted_vocab:
    vocab.append(v[1])
print('vocab', vocab)


vocab ['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '꼬끼리', '원숭이에게', '사과를', '줬어']


In [15]:
for i in range(len(docs)):
    print("문서{} : {}".format(i, docs[i]))
    ICD.display(pd.DataFrame([BoW_ls[i]], columns = vocab))
    print(("\n\n"))

문서0 : 오늘 동물원에서 코끼리 원숭이를 보고 꼬끼리 원숭이에게 사과를 줬어


오늘  동물원에서  코끼리  원숭이를  보고  꼬끼리  원숭이에게  사과를  줬어
0   1      1    1     1   1    1      1    1   1




문서1 : 오늘 동물원에서 원숭이에게 사과를 줬어


오늘  동물원에서  코끼리  원숭이를  보고  꼬끼리  원숭이에게  사과를  줬어
0   1      1    0     0   0    0      1    1   1

In [16]:
BoW_ls

[[1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 0, 0, 0, 0, 1, 1, 1]]

# 단어의 순서를 고려하지 않은 BOW

In [17]:
docs= ['나는 양념 치킨을 좋아해 하지만 후라이드 치킨을 싫어해',
      '나는 후라이드 치킨을 좋아해 하지만 양념 치킨을 싫어해']

In [18]:
doc_ls=[]
for doc in docs:
    doc_ls.append(doc.split())
doc_ls

[['나는', '양념', '치킨을', '좋아해', '하지만', '후라이드', '치킨을', '싫어해'],
 ['나는', '후라이드', '치킨을', '좋아해', '하지만', '양념', '치킨을', '싫어해']]

In [40]:
from collections import defaultdict

word2id = defaultdict(lambda: len(word2id))

for doc in doc_ls:
    for token in doc:
        word2id[token]
word2id


defaultdict(<function __main__.<lambda>>,
            {'나는': 0,
             '싫어해': 6,
             '양념': 1,
             '좋아해': 3,
             '치킨을': 2,
             '하지만': 4,
             '후라이드': 5})

In [19]:
# BOW연습 

In [20]:
docs= ['나는 양념 치킨을 좋아해 하지만 후라이드 치킨을 싫어해',
      '나는 후라이드 치킨을 좋아해 하지만 양념 치킨을 싫어해']

In [22]:
# 띄어쓰기 토큰화

doc_ls=[]
for doc in docs:
    doc_ls.append(doc.split(' '))
print(doc_ls)

[['나는', '양념', '치킨을', '좋아해', '하지만', '후라이드', '치킨을', '싫어해'], ['나는', '후라이드', '치킨을', '좋아해', '하지만', '양념', '치킨을', '싫어해']]


In [26]:
from collections import defaultdict
word2id = defaultdict(lambda:len(word2id))# defaultdict이 중복없애줌

for doc in doc_ls:
    for token in doc:
        word2id[token]
word2id

defaultdict(<function __main__.<lambda>>,
            {'나는': 0,
             '싫어해': 6,
             '양념': 1,
             '좋아해': 3,
             '치킨을': 2,
             '하지만': 4,
             '후라이드': 5})

In [27]:
doc_ls

[['나는', '양념', '치킨을', '좋아해', '하지만', '후라이드', '치킨을', '싫어해'],
 ['나는', '후라이드', '치킨을', '좋아해', '하지만', '양념', '치킨을', '싫어해']]

In [29]:
import numpy as np
BoW_ls=[]
for i, doc in enumerate(doc_ls):
    bow = np.zeros(len(word2id), dtype=int)
    print(bow)
    for token in doc:
        bow[word2id[token]] += 1 # 해당 토큰의위치에 똑같은 토큰이 있으면 +1을 해주
    BoW_ls.append(bow.tolist())
    
BoW_ls

[0 0 0 0 0 0 0]
[0 0 0 0 0 0 0]


[[1, 1, 2, 1, 1, 1, 1], [1, 1, 2, 1, 1, 1, 1]]

In [33]:
from IPython.core import display as ICD
import pandas as pd
sorted_vocab = sorted((value,key) for key, value in word2id.items())
print('sorted_vocab', sorted_vocab)

sorted_vocab [(0, '나는'), (1, '양념'), (2, '치킨을'), (3, '좋아해'), (4, '하지만'), (5, '후라이드'), (6, '싫어해')]


In [35]:
vocab=[]
for v in sorted_vocab:
    vocab.append(v[1])
print('vocab', vocab)


vocab ['나는', '양념', '치킨을', '좋아해', '하지만', '후라이드', '싫어해']


In [37]:
for i in range(len(docs)):
    print("문서{}: {}".format(i,docs[i]))
    ICD.display(pd.DataFrame([BoW_ls[i]],columns=vocab))
    print("\n\n")

문서0: 나는 양념 치킨을 좋아해 하지만 후라이드 치킨을 싫어해


나는  양념  치킨을  좋아해  하지만  후라이드  싫어해
0   1   1    2    1    1     1    1




문서1: 나는 후라이드 치킨을 좋아해 하지만 양념 치킨을 싫어해


나는  양념  치킨을  좋아해  하지만  후라이드  싫어해
0   1   1    2    1    1     1    1

# sklearn을 이용한  BOW 
-CountVectorizer 이거 사용

- fit_frnasform 해주는 작업 필요 

In [43]:
docs=['오늘 동물원에서 코끼리 원숭이를 보고 꼬끼리 원숭이에게 사과를 줬어',
     '오늘 동물원에서 원숭이에게 사과를 줬어']

In [46]:
# 토큰 빈도계산 : CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer
# 선언
count_vect = CountVectorizer()
BoW = count_vect.fit_transform(docs)
print(BoW.toarray())

[[1 1 1 1 1 1 1 1 1]
 [0 1 0 1 1 0 1 1 0]]


In [47]:
vocab = count_vect.get_feature_names()
print(vocab)

['꼬끼리', '동물원에서', '보고', '사과를', '오늘', '원숭이를', '원숭이에게', '줬어', '코끼리']


In [51]:
from IPython.core import display as ICD
import pandas as pd

for i in range(len(docs)):
    print("문서{}: {}".format(i, docs[i]))
    
    print('\n')
    df = pd.DataFrame 

문서0: 오늘 동물원에서 코끼리 원숭이를 보고 꼬끼리 원숭이에게 사과를 줬어


문서1: 오늘 동물원에서 원숭이에게 사과를 줬어




# gensim 사용해서  BOW

In [52]:
docs=['오늘 동물원에서 코끼리 원숭이를 보고 꼬끼리 원숭이에게 사과를 줬어',
     '오늘 동물원에서 원숭이에게 사과를 줬어']

In [53]:
doc_ls

[['나는', '양념', '치킨을', '좋아해', '하지만', '후라이드', '치킨을', '싫어해'],
 ['나는', '후라이드', '치킨을', '좋아해', '하지만', '양념', '치킨을', '싫어해']]

In [54]:
# 리스트로 토큰화 해주고 그 리스트를 딕셔너리에 먼저 넣어 주고(디폴트딕트를 하는것과 같은 원리
# 도큐먼트로 bow 
# 해줘야됨 
# 젠심은 그냥 넣으면 안되고 토큰화 시ㅕ주고 corpora 딕셔너리에 넣어서 유니크한 코ㅇ뽑히ㅔ ㅗ딤 

In [58]:
!pip install gensim
from gensim import corpora

doc_ls=[]
for doc in docs:
    doc_ls.append(doc.split(' '))
print(doc_ls)

[['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '꼬끼리', '원숭이에게', '사과를', '줬어'], ['오늘', '동물원에서', '원숭이에게', '사과를', '줬어']]


In [63]:
id2word = corpora.Dictionary(doc_ls)
print('----')
print(id2word)
BoW = []
for doc in doc_ls:
    BoW.append(id2word.doc2bow(doc))
BoW

----
Dictionary(9 unique tokens: ['꼬끼리', '동물원에서', '보고', '사과를', '오늘']...)


[[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 1), (8, 1)],
 [(1, 1), (3, 1), (4, 1), (6, 1), (7, 1)]]

In [64]:
BoW[0]

[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 1), (8, 1)]

In [66]:
from gensim.matutils import sparse2full
from IPython.core import display as ICD
import pandas as pd
vocab= [id2word[i] for i in id2word.keys()]
for i in range(len(docs)):
    print("문서 {}: {}".format(i, docs[i]))
    ICD.display(pd.DataFrame([sparse2full(BoW[i], len(vocab))], columns =vocab))
    print("\n\n")

문서 0: 오늘 동물원에서 코끼리 원숭이를 보고 꼬끼리 원숭이에게 사과를 줬어


꼬끼리  동물원에서   보고  사과를   오늘  원숭이를  원숭이에게   줬어  코끼리
0  1.0    1.0  1.0  1.0  1.0   1.0    1.0  1.0  1.0




문서 1: 오늘 동물원에서 원숭이에게 사과를 줬어


꼬끼리  동물원에서   보고  사과를   오늘  원숭이를  원숭이에게   줬어  코끼리
0  0.0    1.0  0.0  1.0  1.0   0.0    1.0  1.0  0.0